# NumPy Indexing et Selection

Dans cette session, nous discuterons de la façon de sélectionner des éléments ou des groupes d'éléments à partir d'un tableau.

In [2]:
import numpy as np

In [3]:
# Création d'un tableau simple
arr = np.arange(0,11)

In [4]:
# afficher
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Indexation et sélection
La façon la plus simple de choisir un ou plusieurs éléments d'un tableau ressemble beaucoup aux listes python :

In [5]:
# Obtenir une valeur à un index
arr[8]

8

In [6]:
# Obtenir des valeurs dans une plage d'entiers
arr[1:5]

array([1, 2, 3, 4])

In [7]:
# Obtenir des valeurs dans une plage d'entiers
arr[0:5]

array([0, 1, 2, 3, 4])

## Broadcasting

Les tableaux Numpy diffèrent d'une liste Python normale en raison de leur capacité à diffuser :

In [8]:
# Réglage d'une valeur avec plage d'indice (Broadcasting)
arr[0:5]=100

# afficher
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [9]:
# Réinitialiser le tableau, nous verrons pourquoi 
# j'ai dû le réinitialiser plus bas.
arr = np.arange(0,11)

# afficher
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
# Remarques importantes sur les tranches (slices)
slice_of_arr = arr[0:6]

# afficher tranche
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [11]:
# Changer de tranche
slice_of_arr[:] = 99

# Afficher de nouveau
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Notez maintenant que les changements se produisent aussi dans notre tableau d'origine !

In [12]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Les données ne sont pas copiées, c'est une vue du tableau d'origine ! Cela permet d'éviter les problèmes de mémoire !

In [13]:
# Pour en obtenir une copie, il faut être explicite
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexation d'un tableau 2D (matrices)

Le format général est le suivant **arr_2d[row][col]** ou **arr_2d[row,col]**. Je recommande habituellement d'utiliser la notation par virgule pour plus de clarté.

In [14]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

# afficher
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [15]:
# Indexer une ligne
arr_2d[1]


array([20, 25, 30])

In [16]:
# Le format est arr_2d[row][col] ou arr_2d[row,col]

# Obtenir la valeur d'un élément individuel
arr_2d[1][0]

20

In [17]:
# Obtenir la valeur d'un élément individuel
arr_2d[1,0]

20

In [18]:
# découpage en tranches d'un tableau 2D

# Forme (2,2) du coin supérieur droit
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [19]:
# Forme de la rangée du bas
arr_2d[2]

array([35, 40, 45])

In [20]:
# Forme de la rangée du bas
arr_2d[2,:]

array([35, 40, 45])

## Plus d'aide pour l'indexation
L'indexation d'une matrice 2d peut être un peu confuse au début, surtout lorsque vous commencez à ajouter une taille de pas. Essayez la recherche d'images sur google "NumPy indexing" pour trouver des images utiles, comme celle-ci :

<img src= 'https://s2.qwant.com/thumbr/0x380/e/f/c01bff98594466ebc0010d2898208f123a92d43849fb809db543c82f2038c9/Numpy1.jpg?u=https%3A%2F%2Fmedia.geeksforgeeks.org%2Fwp-content%2Fuploads%2FNumpy1.jpg&q=0&b=1&p=0&a=1' width=500/>

## Sélection conditionnelle

C'est un concept très fondamental qui se réglera directement par pandas plus tard, assurez-vous de bien comprendre cette partie !

Passons brièvement en revue la façon d'utiliser les parenthèses pour la sélection basée sur des opérateurs de comparaison.

In [28]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [31]:
bool_arr = arr>4

In [32]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [33]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [34]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# Bon travail!
